### ISSUE TITLE
Can `ExAws.S3.put_object` support IOdata?

### ISSUE THREAD

**Issue by myronmarston** [ex-aws/ex_aws#305]
When building some binary data piece meal it often performs better to use an `iolist` instead of concatenating binaries.  I tried to use an `iolist` with `ExAws.S3.put_object/4` but it's not supported.

Could ExAws.S3 start supporting the `iodata` type for greater efficiency?

**Comment by benwilson512** [comment]
This seems like a good idea, I'll take a look.

**Comment by benwilson512** [comment]
Closing this. Feel free to make a PR to support this but at the present time I don't have the bandwidth to add it myself.

**Comment by mtwilliams** [comment]
Can you keep this open and tag "good for contributors" @benwilson512?

(I found myself wanting this, but ended up writing glue code to generate a binary through `StringIO`.)

**Comment by benwilson512** [comment]
Can do :)

**Comment by binarylogic** [comment]
We ran into this as well, the request signature does not match the signature AWS is generating. We implemented a workaround by disabling payload signing as shown [here](https://github.com/timberio/ex_aws/commit/518d7e44fe345484208ff2dcb2bf642e11f4e63b). The issue appears to be lower level, most likely `:hackney` from what I could tell. We've had an excessive number of problems with `:hackney` hence my bias towards it being the problem.

That said, if an iolist payload is sent to `:hackney.request/5` the body seen by the receiving service is not equivalent to the result of `:erlang.iolist_to_binary/1`. This is why the signature is invalid. Unfortunately I don't know exactly where the problem lies but I hope this helps someone.
