### ISSUE TITLE
ExAws 2.0

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws#497]
https://elixirforum.com/t/proposal-exaws-2-0/9269

TL;DR: I want to split ExAws up. I'll maintain the core, experts on individual services can maintain the service modules. Everyone gets a better experience because we aren't bottlenecked by my not knowing everything there is to know about every AWS service.

**Comment by mayppong** [comment]
I have been working on the `ex_aws_redshift` package and it's getting close to a usable state. If you could create a repo for me under ex-aws group, I'd be happy to push my code up and maintain that repo instead of my own.

Some notes
- I'm developing with ex_aws version 1 so even if you're not releasing 2 yet, it should still be usable.
- I can add travis CI config file to the project. I just didn't want to set one up for my own repo if I'm going to be transfer the repo over after a few builds.
- The docs and guides are a little barebone but I have some examples written up through doctest. I will be focusing on this as soon as I can get it going with my project at work.
- The functionalities aren't all there. Just basic create/describe/modify/delete of clusters but I will be working on the rest slowly once I caught up with the docs and guides for what's already there.
- Will also put it up on hex.

If you're not able to make the repo for me yet or ever, please let me know so I can get setup and publish the package under my own private repo so I can start using it for work project soon. I just prefer to have it under ex-aws along with the rest of the service packages.

Thanks!
Link for QC: https://github.com/mayppong/ex_aws_redshift

**Comment by fmcgeough** [comment]
@benwilson512 I use ex_aws. Thank you so much for all your work. I need the Elastic Load Balancing API and I've begun taking a stab at a service for it for 2.0. Its at https://github.com/fmcgeough/ex_aws_elastic_load_balancing. Since I was using the ex_aws_ec2 I began modeling it after that but I do notice that each service seems to approach things a bit differently. I guess there is no "right" way and if the service works then, great. It does make it a bit more confusing for people to contribute services though (I think - maybe it's just me). Not sure if this is something that needs to be addressed since each individual/group is going to responsible for their service and so they probably should write them in a way that makes it easiest for them to support it. Any suggestions on how to get this service in best shape, writing tests for it, etc are appreciated.

**Comment by benwilson512** [comment]
Hey folks, small update. We're just about ready to actually release this, I'm mostly gated on trying to finish updating how the default config works. I'm trying to use an `endpoint.json` file published by Amazon to be able to have all services automatically supported in config.

**Comment by benwilson512** [comment]
This has been released!
