### ISSUE TITLE
Feature Request: Support for AWS Translate and AWS ElasticTranscoding.

### ISSUE THREAD

**Issue by collegeimprovements** [ex-aws/ex_aws#579]
Would be great if `ex_aws` can support the following AWS Services.

* AWS Translate: https://console.aws.amazon.com/translate/
* AWS ElasticTranscoding: https://console.aws.amazon.com/elastictranscoder

In case it's not possible, it would be great to have a guideline to implement them with the help of `ex_aws`.
We would be happy if we can be any help or if we can implement it ourselves.

**Comment by benwilson512** [comment]
Since ExAws V2 the core ExAws package is able to make requests to all AWS services via operations. The ExAws core team has no plans for creating additional service modules or projects, but welcomes contributions. If you wish to contribute please see: https://github.com/ex-aws/ex_aws/blob/master/CONTRIBUTING.md
