### ISSUE TITLE
Load configuration dynamically without request failures 

### ISSUE THREAD

**Issue by sheshankkodam** [ex-aws/ex_aws#646]
What is the best way to load the aws configuration dynamically and handle multiple aws requests gracefully? I would like to get the credentials from `IAM` service every hour and use them for the aws requests. 

Currently, I have the configuration loaded from `awscli` and using `os.cmd` to set `aws_access_key_id` and `aws_secret_access_key` as shown below. 

```

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role]


case HTTPoison.get(iam_req_url) do
      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
        resp = body |> Poison.decode!
        :os.cmd('aws configure set aws_access_key_id #{resp["AccessKeyId"]} && 
                 aws configure set aws_secret_access_key #{resp["SecretAccessKey"]}')
       :ok

      {:error, %HTTPoison.Error{reason: reason}} ->
        {:error, reason}
    end
```

### Issues 
I'm seeing 2 issues with this approach 

-  Since updating `aws_access_key_id` and `aws_secret_access_key` might take some time (milliseconds), when the system is under load there is a possibility that few requests may fail. 

- Dependent on `aws_cli` client. For example, an elixir docker image with `aws_cli` client is of size `1.2 GB`. Horizontal scaling with such size is not fast. 

### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.8.1 ( compiled with Erlang/OTP 21)`
* ExAws version `2.1.1`
* HTTP client version. IE for hackney do `1.5.1`

**Comment by benwilson512** [comment]
Hey @sheshankkodam, let's take a look at the questions here in pieces:

## Problem 1: aws-cli is huge.

Solution: Set the keys in the application config instead of via the files on the OS:

```
case HTTPoison.get(iam_req_url) do
      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
        resp = body |> Poison.decode!
        Application.put_env(:ex_aws, :access_key_id, resp["AccessKeyId"])
        Application.put_env(:ex_aws, :secret_access_key, resp["SecretAccessKey"])
       :ok

      {:error, %HTTPoison.Error{reason: reason}} ->
        {:error, reason}
    end
```

The idea here is that instead of writing files to the OS and then waiting on ExAws to pick it up, you can just re-configure ExAws directly.

## Problem 2: Handling requests

Here I need a little bit more information. Are you running on an EC2 instance? If so you should just use ec2 instance iam roles, because then the `:instance_role` option will just work automatically and updates every 15 minutes. There is a similar thing for ECS and Kubernetes that will enable `:instance_role` to work in those cases too.

If you still need to hit IAM roles manually, make the request in your `def start` function within your application module. Set the values as in problem 1 before you actually boot your supervision tree. Then, it's guaranteed that you have some values there before your endpoint is started and you're handling traffic.

**Comment by sheshankkodam** [comment]
Thanks. Will try it.
