### ISSUE TITLE
Emit Telemetry events

### ISSUE THREAD

**Issue by stephanos** [ex-aws/ex_aws#661]
Hello!

[Telemetry](https://github.com/beam-telemetry/telemetry) is getting traction now that it's included in [Phoenix](https://github.com/phoenixframework/phoenix/commit/4d61eacd83d61899a895167715d8754c5c8187be) and [Ecto](https://github.com/elixir-ecto/ecto/commit/ee8a9ea002f8809825d3bd5a3bc34aa863f223ee) out-of-the-box. What's your stance on emitting telemetry events from this library? Would you welcome contributions?

It would allow users of this library to capture important metrics and send them to their monitoring solution. This way, we save everyone the time to instrument their own usage of this library. 

Stephan

**Comment by stephanos** [comment]
Please let me know if you'd be open to merging anything like this so I know my time is well spent :)

**Comment by benwilson512** [comment]
@stephanos I think this could be a valuable contribution, I just think that the main thing to sort out is where to emit events. My inclination is that events should be emitted in the operation `def request` protocol implementation. If we do it in like `def list_objects()` this seems wrong because the operation isn't actually performed at that point in time.

**Comment by stephanos** [comment]
Thanks for the message and pointer! I'll put this on my to do list then :)
Feel free to close this issue if you want, I'll create a PR once I have something presentable.

**Comment by benwilson512** [comment]
Thanks!
